### ISSUE TITLE
Match styling of output to text output

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#29]
The styling used by the bashbook default cell output doesn't quite match the way VSCode renders text output by default.  The default text output is more compact, and I'd argue we should probably do our best to match it.  Here are a couple of screenshots:

Text output:
![image](https://user-images.githubusercontent.com/755842/148938749-315bf946-c7f2-4dbe-b8a6-0cd664f39d93.png)

Bashbook xterm output
![image](https://user-images.githubusercontent.com/755842/148938768-ee4cf923-927e-4109-88c8-1d54fe69cac2.png)

Looks like:

- [x] Bashbook has more padding at top
- [x] Bashbook has less padding at left
- [x] Bashbook font is bigger
- [x] Slight colour difference?
- [ ] Kerning difference?

Here's the relevant dev tools info for text output:

```css
.monaco-workbench .notebookOverlay .output>div.foreground .output-plaintext, .monaco-workbench .notebookOverlay .output>div.foreground .output-stream {
    font-family: var(--notebook-cell-output-font-family);
    white-space: pre-wrap;
    word-wrap: break-word;
}

.monaco-workbench .notebookOverlay .output {
    position: absolute;
    height: 0;
    font-size: var(--notebook-cell-output-font-size);
    user-select: text;
    -webkit-user-select: text;
    -ms-user-select: text;
    cursor: auto;
    box-sizing: border-box;
    z-index: var(--z-index-notebook-output);
}
```

![image](https://user-images.githubusercontent.com/755842/148939872-449e61b6-8f72-480a-b0d6-80f37989fccb.png)
![image](https://user-images.githubusercontent.com/755842/148939873-c46d5328-f124-49cd-a91f-f934213f49cf.png)

**Comment by AndreasArvidsson** [comment]
We can't use that font. On windows that's not even monospace. And we are not trying to match the notebook plain text output were trying to match the vscode terminal aren't we?

Current settings
```css
  color: var(--theme-foreground) !important;
  font-family: var(--theme-code-font-family) !important;
  font-weight: var(--theme-code-font-weight) !important;
  font-size: var(--theme-code-font-size) !important;
```

**Comment by pokey** [comment]
Ah interesting. I guess that's fair then. Do you know if it matches the terminal? Tough to tell because it's behind a canvas. Would be nice to at least lose that top padding

**Comment by AndreasArvidsson** [comment]
Agreed have changed top padding now

**Comment by AndreasArvidsson** [comment]
* Now padding is matching in all directions
* Font matches vscode terminal. Family and size
* I still have some work with colors to do

**Comment by AndreasArvidsson** [comment]
Now all colors match the vscode terminal

**Comment by pokey** [comment]
Reopening because there still appears to be a kerning difference on my screen

![image](https://user-images.githubusercontent.com/755842/149314117-21da3ed0-a645-4780-bccb-6c1a6c61fe70.png)

**Comment by AndreasArvidsson** [comment]
![image](https://user-images.githubusercontent.com/3511326/149352893-0384bdd4-96cc-4a7c-a3e4-cbdcdb0743b5.png)

As a reference this is how it looks on windows

**Comment by AndreasArvidsson** [comment]
@pokey I can't find a single style reference to spacing or kerning. Can you find something on mac?

**Comment by pokey** [comment]
line spacing:

![image](https://user-images.githubusercontent.com/755842/152340832-78930f45-9924-43cd-986e-10859d3de6b0.png)

```css
.xterm-dom-renderer-owner-2 .xterm-rows span {
    display: inline-block;
    height: 100%;
    vertical-align: top;
    width: 9.0125px; // <-- remove me
}
```
